rules:
  - name: Auto-merge documentation updates
    conditions:
      - base=main
      - label=documentation
      - label=size/XS
      - label=lgtm
      - status-success=ci
      - status-success=pr-checks
    actions:
      queue:
        method: rebase
        update_branch: true
      merge:
        method: squash
        commit_message: "docs: {{ title }}"

  - name: Auto-merge dependency updates
    conditions:
      - base=main
      - label=dependencies
      - label=lgtm
      - status-success=ci
      - status-success=pr-checks
    actions:
      queue:
        method: rebase
        update_branch: true
      merge:
        method: squash
        commit_message: "deps: {{ title }}"

  - name: Auto-merge small fixes
    conditions:
      - base=main
      - label=size/XS
      - label=bug
      - label=lgtm
      - status-success=ci
      - status-success=pr-checks
    actions:
      queue:
        method: rebase
        update_branch: true
      merge:
        method: squash
        commit_message: "fix: {{ title }}"

  - name: Auto-merge CI/CD improvements
    conditions:
      - base=main
      - label=ci-cd
      - label=size/XS
      - label=lgtm
      - status-success=ci
      - status-success=pr-checks
    actions:
      queue:
        method: rebase
        update_branch: true
      merge:
        method: squash
        commit_message: "ci: {{ title }}"

  - name: Auto-merge frontend changes
    conditions:
      - base=main
      - label=frontend
      - label=lgtm
      - status-success=ci
      - status-success=pr-checks
    actions:
      queue:
        method: rebase
        update_branch: true
      merge:
        method: squash
        commit_message: "feat: {{ title }}"

  - name: Auto-merge ML/AI changes
    conditions:
      - base=main
      - label=ai-ml
      - label=lgtm
      - status-success=ci
      - status-success=pr-checks
    actions:
      queue:
        method: rebase
        update_branch: true
      merge:
        method: squash
        commit_message: "feat: {{ title }}" 