version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Arpit529Srivastava"
      - "Shrey327"
    assignees:
      - "Arpit529Srivastava"
      - "Shrey327"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/ai"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Shrey327"
      - "Arpit529Srivastava"
    assignees:
      - "Arpit529Srivastava"
      - "Shrey327"
    labels:
      - "dependencies"
      - "python"
      - "ai-ml"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Shrey327"
      - "Arpit529Srivastava"
    assignees:
      - "Shrey327"
      - "Arpit529Srivastava"
    labels:
      - "dependencies"
      - "frontend"  
      - "web"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Arpit529Srivastava"
    assignees:
      - "Arpit529Srivastava"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Arpit529Srivastava"
    assignees:
      - "Arpit529Srivastava"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps"
      include: "scope" 