server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 30s

database:
  host: localhost
  port: 5432
  user: driftguard
  password: password
  dbname: driftguard
  sslmode: disable
  max_conns: 10

kubernetes:
  config_path: ""
  context: ""
  namespaces: ["default"]
  resources: ["deployments", "services", "configmaps", "secrets"]
  labels: {}

git:
  default_branch: main
  clone_timeout: 5m
  pull_timeout: 2m

mcp:
  endpoint: localhost:9000
  timeout: 30s
  retries: 3

environments:
  - name: development
    description: Development environment
    labels:
      env: dev
    git_repo:
      url: "https://github.com/example/k8s-configs"
      branch: main
      path: k8s/dev
    k8s_context: dev-cluster

logging:
  level: info
  format: json
  output_path: "" 